
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point SCL SCL -type PI PI
add mapped point A_0 A_0 -type PI PI
add mapped point A_1 A_1 -type PI PI
add mapped point A_2 A_2 -type PI PI
add mapped point ADC_in[2][7] ADC_in[2][7] -type PI PI
add mapped point ADC_in[2][6] ADC_in[2][6] -type PI PI
add mapped point ADC_in[2][5] ADC_in[2][5] -type PI PI
add mapped point ADC_in[2][4] ADC_in[2][4] -type PI PI
add mapped point ADC_in[2][3] ADC_in[2][3] -type PI PI
add mapped point ADC_in[2][2] ADC_in[2][2] -type PI PI
add mapped point ADC_in[2][1] ADC_in[2][1] -type PI PI
add mapped point ADC_in[2][0] ADC_in[2][0] -type PI PI
add mapped point ADC_in[1][7] ADC_in[1][7] -type PI PI
add mapped point ADC_in[1][6] ADC_in[1][6] -type PI PI
add mapped point ADC_in[1][5] ADC_in[1][5] -type PI PI
add mapped point ADC_in[1][4] ADC_in[1][4] -type PI PI
add mapped point ADC_in[1][3] ADC_in[1][3] -type PI PI
add mapped point ADC_in[1][2] ADC_in[1][2] -type PI PI
add mapped point ADC_in[1][1] ADC_in[1][1] -type PI PI
add mapped point ADC_in[1][0] ADC_in[1][0] -type PI PI
add mapped point ADC_in[0][7] ADC_in[0][7] -type PI PI
add mapped point ADC_in[0][6] ADC_in[0][6] -type PI PI
add mapped point ADC_in[0][5] ADC_in[0][5] -type PI PI
add mapped point ADC_in[0][4] ADC_in[0][4] -type PI PI
add mapped point ADC_in[0][3] ADC_in[0][3] -type PI PI
add mapped point ADC_in[0][2] ADC_in[0][2] -type PI PI
add mapped point ADC_in[0][1] ADC_in[0][1] -type PI PI
add mapped point ADC_in[0][0] ADC_in[0][0] -type PI PI

//output ports
add mapped point DAC_out[30][7] DAC_out[30][7] -type PO PO
add mapped point DAC_out[30][6] DAC_out[30][6] -type PO PO
add mapped point DAC_out[30][5] DAC_out[30][5] -type PO PO
add mapped point DAC_out[30][4] DAC_out[30][4] -type PO PO
add mapped point DAC_out[30][3] DAC_out[30][3] -type PO PO
add mapped point DAC_out[30][2] DAC_out[30][2] -type PO PO
add mapped point DAC_out[30][1] DAC_out[30][1] -type PO PO
add mapped point DAC_out[30][0] DAC_out[30][0] -type PO PO
add mapped point DAC_out[29][7] DAC_out[29][7] -type PO PO
add mapped point DAC_out[29][6] DAC_out[29][6] -type PO PO
add mapped point DAC_out[29][5] DAC_out[29][5] -type PO PO
add mapped point DAC_out[29][4] DAC_out[29][4] -type PO PO
add mapped point DAC_out[29][3] DAC_out[29][3] -type PO PO
add mapped point DAC_out[29][2] DAC_out[29][2] -type PO PO
add mapped point DAC_out[29][1] DAC_out[29][1] -type PO PO
add mapped point DAC_out[29][0] DAC_out[29][0] -type PO PO
add mapped point DAC_out[28][7] DAC_out[28][7] -type PO PO
add mapped point DAC_out[28][6] DAC_out[28][6] -type PO PO
add mapped point DAC_out[28][5] DAC_out[28][5] -type PO PO
add mapped point DAC_out[28][4] DAC_out[28][4] -type PO PO
add mapped point DAC_out[28][3] DAC_out[28][3] -type PO PO
add mapped point DAC_out[28][2] DAC_out[28][2] -type PO PO
add mapped point DAC_out[28][1] DAC_out[28][1] -type PO PO
add mapped point DAC_out[28][0] DAC_out[28][0] -type PO PO
add mapped point DAC_out[27][7] DAC_out[27][7] -type PO PO
add mapped point DAC_out[27][6] DAC_out[27][6] -type PO PO
add mapped point DAC_out[27][5] DAC_out[27][5] -type PO PO
add mapped point DAC_out[27][4] DAC_out[27][4] -type PO PO
add mapped point DAC_out[27][3] DAC_out[27][3] -type PO PO
add mapped point DAC_out[27][2] DAC_out[27][2] -type PO PO
add mapped point DAC_out[27][1] DAC_out[27][1] -type PO PO
add mapped point DAC_out[27][0] DAC_out[27][0] -type PO PO
add mapped point DAC_out[26][7] DAC_out[26][7] -type PO PO
add mapped point DAC_out[26][6] DAC_out[26][6] -type PO PO
add mapped point DAC_out[26][5] DAC_out[26][5] -type PO PO
add mapped point DAC_out[26][4] DAC_out[26][4] -type PO PO
add mapped point DAC_out[26][3] DAC_out[26][3] -type PO PO
add mapped point DAC_out[26][2] DAC_out[26][2] -type PO PO
add mapped point DAC_out[26][1] DAC_out[26][1] -type PO PO
add mapped point DAC_out[26][0] DAC_out[26][0] -type PO PO
add mapped point DAC_out[25][7] DAC_out[25][7] -type PO PO
add mapped point DAC_out[25][6] DAC_out[25][6] -type PO PO
add mapped point DAC_out[25][5] DAC_out[25][5] -type PO PO
add mapped point DAC_out[25][4] DAC_out[25][4] -type PO PO
add mapped point DAC_out[25][3] DAC_out[25][3] -type PO PO
add mapped point DAC_out[25][2] DAC_out[25][2] -type PO PO
add mapped point DAC_out[25][1] DAC_out[25][1] -type PO PO
add mapped point DAC_out[25][0] DAC_out[25][0] -type PO PO
add mapped point DAC_out[24][7] DAC_out[24][7] -type PO PO
add mapped point DAC_out[24][6] DAC_out[24][6] -type PO PO
add mapped point DAC_out[24][5] DAC_out[24][5] -type PO PO
add mapped point DAC_out[24][4] DAC_out[24][4] -type PO PO
add mapped point DAC_out[24][3] DAC_out[24][3] -type PO PO
add mapped point DAC_out[24][2] DAC_out[24][2] -type PO PO
add mapped point DAC_out[24][1] DAC_out[24][1] -type PO PO
add mapped point DAC_out[24][0] DAC_out[24][0] -type PO PO
add mapped point DAC_out[23][7] DAC_out[23][7] -type PO PO
add mapped point DAC_out[23][6] DAC_out[23][6] -type PO PO
add mapped point DAC_out[23][5] DAC_out[23][5] -type PO PO
add mapped point DAC_out[23][4] DAC_out[23][4] -type PO PO
add mapped point DAC_out[23][3] DAC_out[23][3] -type PO PO
add mapped point DAC_out[23][2] DAC_out[23][2] -type PO PO
add mapped point DAC_out[23][1] DAC_out[23][1] -type PO PO
add mapped point DAC_out[23][0] DAC_out[23][0] -type PO PO
add mapped point DAC_out[22][7] DAC_out[22][7] -type PO PO
add mapped point DAC_out[22][6] DAC_out[22][6] -type PO PO
add mapped point DAC_out[22][5] DAC_out[22][5] -type PO PO
add mapped point DAC_out[22][4] DAC_out[22][4] -type PO PO
add mapped point DAC_out[22][3] DAC_out[22][3] -type PO PO
add mapped point DAC_out[22][2] DAC_out[22][2] -type PO PO
add mapped point DAC_out[22][1] DAC_out[22][1] -type PO PO
add mapped point DAC_out[22][0] DAC_out[22][0] -type PO PO
add mapped point DAC_out[21][7] DAC_out[21][7] -type PO PO
add mapped point DAC_out[21][6] DAC_out[21][6] -type PO PO
add mapped point DAC_out[21][5] DAC_out[21][5] -type PO PO
add mapped point DAC_out[21][4] DAC_out[21][4] -type PO PO
add mapped point DAC_out[21][3] DAC_out[21][3] -type PO PO
add mapped point DAC_out[21][2] DAC_out[21][2] -type PO PO
add mapped point DAC_out[21][1] DAC_out[21][1] -type PO PO
add mapped point DAC_out[21][0] DAC_out[21][0] -type PO PO
add mapped point DAC_out[20][7] DAC_out[20][7] -type PO PO
add mapped point DAC_out[20][6] DAC_out[20][6] -type PO PO
add mapped point DAC_out[20][5] DAC_out[20][5] -type PO PO
add mapped point DAC_out[20][4] DAC_out[20][4] -type PO PO
add mapped point DAC_out[20][3] DAC_out[20][3] -type PO PO
add mapped point DAC_out[20][2] DAC_out[20][2] -type PO PO
add mapped point DAC_out[20][1] DAC_out[20][1] -type PO PO
add mapped point DAC_out[20][0] DAC_out[20][0] -type PO PO
add mapped point DAC_out[19][7] DAC_out[19][7] -type PO PO
add mapped point DAC_out[19][6] DAC_out[19][6] -type PO PO
add mapped point DAC_out[19][5] DAC_out[19][5] -type PO PO
add mapped point DAC_out[19][4] DAC_out[19][4] -type PO PO
add mapped point DAC_out[19][3] DAC_out[19][3] -type PO PO
add mapped point DAC_out[19][2] DAC_out[19][2] -type PO PO
add mapped point DAC_out[19][1] DAC_out[19][1] -type PO PO
add mapped point DAC_out[19][0] DAC_out[19][0] -type PO PO
add mapped point DAC_out[18][7] DAC_out[18][7] -type PO PO
add mapped point DAC_out[18][6] DAC_out[18][6] -type PO PO
add mapped point DAC_out[18][5] DAC_out[18][5] -type PO PO
add mapped point DAC_out[18][4] DAC_out[18][4] -type PO PO
add mapped point DAC_out[18][3] DAC_out[18][3] -type PO PO
add mapped point DAC_out[18][2] DAC_out[18][2] -type PO PO
add mapped point DAC_out[18][1] DAC_out[18][1] -type PO PO
add mapped point DAC_out[18][0] DAC_out[18][0] -type PO PO
add mapped point DAC_out[17][7] DAC_out[17][7] -type PO PO
add mapped point DAC_out[17][6] DAC_out[17][6] -type PO PO
add mapped point DAC_out[17][5] DAC_out[17][5] -type PO PO
add mapped point DAC_out[17][4] DAC_out[17][4] -type PO PO
add mapped point DAC_out[17][3] DAC_out[17][3] -type PO PO
add mapped point DAC_out[17][2] DAC_out[17][2] -type PO PO
add mapped point DAC_out[17][1] DAC_out[17][1] -type PO PO
add mapped point DAC_out[17][0] DAC_out[17][0] -type PO PO
add mapped point DAC_out[16][7] DAC_out[16][7] -type PO PO
add mapped point DAC_out[16][6] DAC_out[16][6] -type PO PO
add mapped point DAC_out[16][5] DAC_out[16][5] -type PO PO
add mapped point DAC_out[16][4] DAC_out[16][4] -type PO PO
add mapped point DAC_out[16][3] DAC_out[16][3] -type PO PO
add mapped point DAC_out[16][2] DAC_out[16][2] -type PO PO
add mapped point DAC_out[16][1] DAC_out[16][1] -type PO PO
add mapped point DAC_out[16][0] DAC_out[16][0] -type PO PO
add mapped point DAC_out[15][7] DAC_out[15][7] -type PO PO
add mapped point DAC_out[15][6] DAC_out[15][6] -type PO PO
add mapped point DAC_out[15][5] DAC_out[15][5] -type PO PO
add mapped point DAC_out[15][4] DAC_out[15][4] -type PO PO
add mapped point DAC_out[15][3] DAC_out[15][3] -type PO PO
add mapped point DAC_out[15][2] DAC_out[15][2] -type PO PO
add mapped point DAC_out[15][1] DAC_out[15][1] -type PO PO
add mapped point DAC_out[15][0] DAC_out[15][0] -type PO PO
add mapped point DAC_out[14][7] DAC_out[14][7] -type PO PO
add mapped point DAC_out[14][6] DAC_out[14][6] -type PO PO
add mapped point DAC_out[14][5] DAC_out[14][5] -type PO PO
add mapped point DAC_out[14][4] DAC_out[14][4] -type PO PO
add mapped point DAC_out[14][3] DAC_out[14][3] -type PO PO
add mapped point DAC_out[14][2] DAC_out[14][2] -type PO PO
add mapped point DAC_out[14][1] DAC_out[14][1] -type PO PO
add mapped point DAC_out[14][0] DAC_out[14][0] -type PO PO
add mapped point DAC_out[13][7] DAC_out[13][7] -type PO PO
add mapped point DAC_out[13][6] DAC_out[13][6] -type PO PO
add mapped point DAC_out[13][5] DAC_out[13][5] -type PO PO
add mapped point DAC_out[13][4] DAC_out[13][4] -type PO PO
add mapped point DAC_out[13][3] DAC_out[13][3] -type PO PO
add mapped point DAC_out[13][2] DAC_out[13][2] -type PO PO
add mapped point DAC_out[13][1] DAC_out[13][1] -type PO PO
add mapped point DAC_out[13][0] DAC_out[13][0] -type PO PO
add mapped point DAC_out[12][7] DAC_out[12][7] -type PO PO
add mapped point DAC_out[12][6] DAC_out[12][6] -type PO PO
add mapped point DAC_out[12][5] DAC_out[12][5] -type PO PO
add mapped point DAC_out[12][4] DAC_out[12][4] -type PO PO
add mapped point DAC_out[12][3] DAC_out[12][3] -type PO PO
add mapped point DAC_out[12][2] DAC_out[12][2] -type PO PO
add mapped point DAC_out[12][1] DAC_out[12][1] -type PO PO
add mapped point DAC_out[12][0] DAC_out[12][0] -type PO PO
add mapped point DAC_out[11][7] DAC_out[11][7] -type PO PO
add mapped point DAC_out[11][6] DAC_out[11][6] -type PO PO
add mapped point DAC_out[11][5] DAC_out[11][5] -type PO PO
add mapped point DAC_out[11][4] DAC_out[11][4] -type PO PO
add mapped point DAC_out[11][3] DAC_out[11][3] -type PO PO
add mapped point DAC_out[11][2] DAC_out[11][2] -type PO PO
add mapped point DAC_out[11][1] DAC_out[11][1] -type PO PO
add mapped point DAC_out[11][0] DAC_out[11][0] -type PO PO
add mapped point DAC_out[10][7] DAC_out[10][7] -type PO PO
add mapped point DAC_out[10][6] DAC_out[10][6] -type PO PO
add mapped point DAC_out[10][5] DAC_out[10][5] -type PO PO
add mapped point DAC_out[10][4] DAC_out[10][4] -type PO PO
add mapped point DAC_out[10][3] DAC_out[10][3] -type PO PO
add mapped point DAC_out[10][2] DAC_out[10][2] -type PO PO
add mapped point DAC_out[10][1] DAC_out[10][1] -type PO PO
add mapped point DAC_out[10][0] DAC_out[10][0] -type PO PO
add mapped point DAC_out[9][7] DAC_out[9][7] -type PO PO
add mapped point DAC_out[9][6] DAC_out[9][6] -type PO PO
add mapped point DAC_out[9][5] DAC_out[9][5] -type PO PO
add mapped point DAC_out[9][4] DAC_out[9][4] -type PO PO
add mapped point DAC_out[9][3] DAC_out[9][3] -type PO PO
add mapped point DAC_out[9][2] DAC_out[9][2] -type PO PO
add mapped point DAC_out[9][1] DAC_out[9][1] -type PO PO
add mapped point DAC_out[9][0] DAC_out[9][0] -type PO PO
add mapped point DAC_out[8][7] DAC_out[8][7] -type PO PO
add mapped point DAC_out[8][6] DAC_out[8][6] -type PO PO
add mapped point DAC_out[8][5] DAC_out[8][5] -type PO PO
add mapped point DAC_out[8][4] DAC_out[8][4] -type PO PO
add mapped point DAC_out[8][3] DAC_out[8][3] -type PO PO
add mapped point DAC_out[8][2] DAC_out[8][2] -type PO PO
add mapped point DAC_out[8][1] DAC_out[8][1] -type PO PO
add mapped point DAC_out[8][0] DAC_out[8][0] -type PO PO
add mapped point DAC_out[7][7] DAC_out[7][7] -type PO PO
add mapped point DAC_out[7][6] DAC_out[7][6] -type PO PO
add mapped point DAC_out[7][5] DAC_out[7][5] -type PO PO
add mapped point DAC_out[7][4] DAC_out[7][4] -type PO PO
add mapped point DAC_out[7][3] DAC_out[7][3] -type PO PO
add mapped point DAC_out[7][2] DAC_out[7][2] -type PO PO
add mapped point DAC_out[7][1] DAC_out[7][1] -type PO PO
add mapped point DAC_out[7][0] DAC_out[7][0] -type PO PO
add mapped point DAC_out[6][7] DAC_out[6][7] -type PO PO
add mapped point DAC_out[6][6] DAC_out[6][6] -type PO PO
add mapped point DAC_out[6][5] DAC_out[6][5] -type PO PO
add mapped point DAC_out[6][4] DAC_out[6][4] -type PO PO
add mapped point DAC_out[6][3] DAC_out[6][3] -type PO PO
add mapped point DAC_out[6][2] DAC_out[6][2] -type PO PO
add mapped point DAC_out[6][1] DAC_out[6][1] -type PO PO
add mapped point DAC_out[6][0] DAC_out[6][0] -type PO PO
add mapped point DAC_out[5][7] DAC_out[5][7] -type PO PO
add mapped point DAC_out[5][6] DAC_out[5][6] -type PO PO
add mapped point DAC_out[5][5] DAC_out[5][5] -type PO PO
add mapped point DAC_out[5][4] DAC_out[5][4] -type PO PO
add mapped point DAC_out[5][3] DAC_out[5][3] -type PO PO
add mapped point DAC_out[5][2] DAC_out[5][2] -type PO PO
add mapped point DAC_out[5][1] DAC_out[5][1] -type PO PO
add mapped point DAC_out[5][0] DAC_out[5][0] -type PO PO
add mapped point DAC_out[4][7] DAC_out[4][7] -type PO PO
add mapped point DAC_out[4][6] DAC_out[4][6] -type PO PO
add mapped point DAC_out[4][5] DAC_out[4][5] -type PO PO
add mapped point DAC_out[4][4] DAC_out[4][4] -type PO PO
add mapped point DAC_out[4][3] DAC_out[4][3] -type PO PO
add mapped point DAC_out[4][2] DAC_out[4][2] -type PO PO
add mapped point DAC_out[4][1] DAC_out[4][1] -type PO PO
add mapped point DAC_out[4][0] DAC_out[4][0] -type PO PO
add mapped point DAC_out[3][7] DAC_out[3][7] -type PO PO
add mapped point DAC_out[3][6] DAC_out[3][6] -type PO PO
add mapped point DAC_out[3][5] DAC_out[3][5] -type PO PO
add mapped point DAC_out[3][4] DAC_out[3][4] -type PO PO
add mapped point DAC_out[3][3] DAC_out[3][3] -type PO PO
add mapped point DAC_out[3][2] DAC_out[3][2] -type PO PO
add mapped point DAC_out[3][1] DAC_out[3][1] -type PO PO
add mapped point DAC_out[3][0] DAC_out[3][0] -type PO PO
add mapped point DAC_out[2][7] DAC_out[2][7] -type PO PO
add mapped point DAC_out[2][6] DAC_out[2][6] -type PO PO
add mapped point DAC_out[2][5] DAC_out[2][5] -type PO PO
add mapped point DAC_out[2][4] DAC_out[2][4] -type PO PO
add mapped point DAC_out[2][3] DAC_out[2][3] -type PO PO
add mapped point DAC_out[2][2] DAC_out[2][2] -type PO PO
add mapped point DAC_out[2][1] DAC_out[2][1] -type PO PO
add mapped point DAC_out[2][0] DAC_out[2][0] -type PO PO
add mapped point DAC_out[1][7] DAC_out[1][7] -type PO PO
add mapped point DAC_out[1][6] DAC_out[1][6] -type PO PO
add mapped point DAC_out[1][5] DAC_out[1][5] -type PO PO
add mapped point DAC_out[1][4] DAC_out[1][4] -type PO PO
add mapped point DAC_out[1][3] DAC_out[1][3] -type PO PO
add mapped point DAC_out[1][2] DAC_out[1][2] -type PO PO
add mapped point DAC_out[1][1] DAC_out[1][1] -type PO PO
add mapped point DAC_out[1][0] DAC_out[1][0] -type PO PO
add mapped point DAC_out[0][7] DAC_out[0][7] -type PO PO
add mapped point DAC_out[0][6] DAC_out[0][6] -type PO PO
add mapped point DAC_out[0][5] DAC_out[0][5] -type PO PO
add mapped point DAC_out[0][4] DAC_out[0][4] -type PO PO
add mapped point DAC_out[0][3] DAC_out[0][3] -type PO PO
add mapped point DAC_out[0][2] DAC_out[0][2] -type PO PO
add mapped point DAC_out[0][1] DAC_out[0][1] -type PO PO
add mapped point DAC_out[0][0] DAC_out[0][0] -type PO PO
add mapped point CS_control[2][2] CS_control[2][2] -type PO PO
add mapped point CS_control[2][1] CS_control[2][1] -type PO PO
add mapped point CS_control[2][0] CS_control[2][0] -type PO PO
add mapped point CS_control[1][2] CS_control[1][2] -type PO PO
add mapped point CS_control[1][1] CS_control[1][1] -type PO PO
add mapped point CS_control[1][0] CS_control[1][0] -type PO PO
add mapped point CS_control[0][2] CS_control[0][2] -type PO PO
add mapped point CS_control[0][1] CS_control[0][1] -type PO PO
add mapped point CS_control[0][0] CS_control[0][0] -type PO PO
add mapped point CP_reset[2] CP_reset[2] -type PO PO
add mapped point CP_reset[1] CP_reset[1] -type PO PO
add mapped point CP_reset[0] CP_reset[0] -type PO PO
add mapped point Timer_EN[2] Timer_EN[2] -type PO PO
add mapped point Timer_EN[1] Timer_EN[1] -type PO PO
add mapped point Timer_EN[0] Timer_EN[0] -type PO PO
add mapped point Timer_FEN[2] Timer_FEN[2] -type PO PO
add mapped point Timer_FEN[1] Timer_FEN[1] -type PO PO
add mapped point Timer_FEN[0] Timer_FEN[0] -type PO PO
add mapped point Amp_EN[2] Amp_EN[2] -type PO PO
add mapped point Amp_EN[1] Amp_EN[1] -type PO PO
add mapped point Amp_EN[0] Amp_EN[0] -type PO PO

//inout ports
add mapped point SDA SDA




//Sequential Pins
add mapped point i2c_inst/rw_bit/q i2c_inst/rw_bit_reg/Q -type DFF DFF
add mapped point i2c_inst/clk_cnt[1]/q i2c_inst/clk_cnt_reg[1]/Q -type DFF DFF
add mapped point i2c_inst/clk_cnt[0]/q i2c_inst/clk_cnt_reg[0]/Q -type DFF DFF
add mapped point i2c_inst/shift_reg[0]/q i2c_inst/shift_reg_reg[0]/Q -type DFF DFF
add mapped point i2c_inst/bit_cnt[2]/q i2c_inst/bit_cnt_reg[2]/Q -type DFF DFF
add mapped point i2c_inst/bit_cnt[1]/q i2c_inst/bit_cnt_reg[1]/Q -type DFF DFF
add mapped point i2c_inst/sda_sync[1]/q i2c_inst/sda_sync_reg[1]/Q -type DFF DFF
add mapped point i2c_inst/bit_cnt[0]/q i2c_inst/bit_cnt_reg[0]/Q -type DFF DFF
add mapped point i2c_inst/bit_cnt[3]/q i2c_inst/bit_cnt_reg[3]/Q -type DFF DFF
add mapped point i2c_inst/state[3]/q i2c_inst/state_reg[3]/Q -type DFF DFF
add mapped point i2c_inst/sda_sync[0]/q i2c_inst/sda_sync_reg[0]/Q -type DFF DFF
add mapped point i2c_inst/Reg_read/q i2c_inst/Reg_read_reg/Q -type DFF DFF
add mapped point i2c_inst/Reg_write/q i2c_inst/Reg_write_reg/Q -type DFF DFF
add mapped point i2c_inst/state[2]/q i2c_inst/state_reg[2]/Q -type DFF DFF
add mapped point i2c_inst/state[1]/q i2c_inst/state_reg[1]/Q -type DFF DFF
add mapped point i2c_inst/Data_out[7]/q i2c_inst/Data_out_reg[7]/Q -type DFF DFF
add mapped point i2c_inst/Data_out[3]/q i2c_inst/Data_out_reg[3]/Q -type DFF DFF
add mapped point i2c_inst/Data_out[2]/q i2c_inst/Data_out_reg[2]/Q -type DFF DFF
add mapped point i2c_inst/Data_out[5]/q i2c_inst/Data_out_reg[5]/Q -type DFF DFF
add mapped point i2c_inst/Reg_addr[3]/q i2c_inst/Reg_addr_reg[3]/Q -type DFF DFF
add mapped point i2c_inst/Data_out[4]/q i2c_inst/Data_out_reg[4]/Q -type DFF DFF
add mapped point i2c_inst/Data_out[1]/q i2c_inst/Data_out_reg[1]/Q -type DFF DFF
add mapped point i2c_inst/state[0]/q i2c_inst/state_reg[0]/Q -type DFF DFF
add mapped point i2c_inst/Reg_addr[1]/q i2c_inst/Reg_addr_reg[1]/Q -type DFF DFF
add mapped point i2c_inst/Reg_addr[2]/q i2c_inst/Reg_addr_reg[2]/Q -type DFF DFF
add mapped point i2c_inst/Data_out[0]/q i2c_inst/Data_out_reg[0]/Q -type DFF DFF
add mapped point i2c_inst/Reg_addr[4]/q i2c_inst/Reg_addr_reg[4]/Q -type DFF DFF
add mapped point i2c_inst/Reg_addr[5]/q i2c_inst/Reg_addr_reg[5]/Q -type DFF DFF
add mapped point i2c_inst/Data_out[6]/q i2c_inst/Data_out_reg[6]/Q -type DFF DFF
add mapped point i2c_inst/Reg_addr[0]/q i2c_inst/Reg_addr_reg[0]/Q -type DFF DFF
add mapped point i2c_inst/shift_reg[7]/q i2c_inst/shift_reg_reg[7]/Q -type DFF DFF
add mapped point i2c_inst/shift_reg[6]/q i2c_inst/shift_reg_reg[6]/Q -type DFF DFF
add mapped point i2c_inst/shift_reg[5]/q i2c_inst/shift_reg_reg[5]/Q -type DFF DFF
add mapped point i2c_inst/shift_reg[4]/q i2c_inst/shift_reg_reg[4]/Q -type DFF DFF
add mapped point i2c_inst/shift_reg[2]/q i2c_inst/shift_reg_reg[2]/Q -type DFF DFF
add mapped point i2c_inst/shift_reg[1]/q i2c_inst/shift_reg_reg[1]/Q -type DFF DFF
add mapped point i2c_inst/shift_reg[3]/q i2c_inst/shift_reg_reg[3]/Q -type DFF DFF
add mapped point i2c_inst/sda_out_tri_enable_reg/q i2c_inst/sda_out_reg297/Q -type DFF DFF
add mapped point i2c_inst/read_only_reg/q i2c_inst/read_only_reg_reg/Q -type DFF DFF
add mapped point i2c_inst/stop_cond/q i2c_inst/stop_cond_reg/Q -type DFF DFF
add mapped point i2c_inst/start_cond/q i2c_inst/start_cond_reg/Q -type DFF DFF
add mapped point i2c_inst/sda_en/q i2c_inst/sda_en_reg/Q -type DFF DFF
add mapped point i2c_inst/scl_rising/q i2c_inst/scl_rising_reg/Q -type DFF DFF
add mapped point i2c_inst/scl_falling/q i2c_inst/scl_falling_reg/Q -type DFF DFF
add mapped point i2c_inst/scl_sync[2]/q i2c_inst/scl_sync_reg[2]/Q -type DFF DFF
add mapped point i2c_inst/scl_sync[1]/q i2c_inst/scl_sync_reg[1]/Q -type DFF DFF
add mapped point i2c_inst/sda_sync[2]/q i2c_inst/sda_sync_reg[2]/Q -type DFF DFF
add mapped point i2c_inst/scl_sync[0]/q i2c_inst/scl_sync_reg[0]/Q -type DFF DFF
add mapped point mem_inst/Amp_EN[0]/q mem_inst/Amp_EN_reg[0]/Q -type DFF DFF
add mapped point mem_inst/Amp_EN[1]/q mem_inst/Amp_EN_reg[1]/Q -type DFF DFF
add mapped point mem_inst/Amp_EN[2]/q mem_inst/Amp_EN_reg[2]/Q -type DFF DFF
add mapped point mem_inst/CP_reset[0]/q mem_inst/CP_reset_reg[0]/Q -type DFF DFF
add mapped point mem_inst/CP_reset[1]/q mem_inst/CP_reset_reg[1]/Q -type DFF DFF
add mapped point mem_inst/CP_reset[2]/q mem_inst/CP_reset_reg[2]/Q -type DFF DFF
add mapped point mem_inst/CS_control[0][0]/q mem_inst/CS_control_reg[0][0]/Q -type DFF DFF
add mapped point mem_inst/CS_control[0][1]/q mem_inst/CS_control_reg[0][1]/Q -type DFF DFF
add mapped point mem_inst/CS_control[0][2]/q mem_inst/CS_control_reg[0][2]/Q -type DFF DFF
add mapped point mem_inst/CS_control[1][0]/q mem_inst/CS_control_reg[1][0]/Q -type DFF DFF
add mapped point mem_inst/CS_control[1][1]/q mem_inst/CS_control_reg[1][1]/Q -type DFF DFF
add mapped point mem_inst/CS_control[1][2]/q mem_inst/CS_control_reg[1][2]/Q -type DFF DFF
add mapped point mem_inst/CS_control[2][0]/q mem_inst/CS_control_reg[2][0]/Q -type DFF DFF
add mapped point mem_inst/CS_control[2][1]/q mem_inst/CS_control_reg[2][1]/Q -type DFF DFF
add mapped point mem_inst/CS_control[2][2]/q mem_inst/CS_control_reg[2][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[0][0]/q mem_inst/DAC_out_reg[0][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[0][1]/q mem_inst/DAC_out_reg[0][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[0][2]/q mem_inst/DAC_out_reg[0][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[0][3]/q mem_inst/DAC_out_reg[0][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[0][4]/q mem_inst/DAC_out_reg[0][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[0][5]/q mem_inst/DAC_out_reg[0][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[0][6]/q mem_inst/DAC_out_reg[0][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[0][7]/q mem_inst/DAC_out_reg[0][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[1][0]/q mem_inst/DAC_out_reg[1][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[1][1]/q mem_inst/DAC_out_reg[1][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[1][2]/q mem_inst/DAC_out_reg[1][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[1][3]/q mem_inst/DAC_out_reg[1][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[1][4]/q mem_inst/DAC_out_reg[1][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[1][5]/q mem_inst/DAC_out_reg[1][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[1][6]/q mem_inst/DAC_out_reg[1][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[1][7]/q mem_inst/DAC_out_reg[1][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[2][0]/q mem_inst/DAC_out_reg[2][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[2][1]/q mem_inst/DAC_out_reg[2][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[2][2]/q mem_inst/DAC_out_reg[2][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[2][3]/q mem_inst/DAC_out_reg[2][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[2][4]/q mem_inst/DAC_out_reg[2][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[2][5]/q mem_inst/DAC_out_reg[2][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[2][6]/q mem_inst/DAC_out_reg[2][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[2][7]/q mem_inst/DAC_out_reg[2][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[3][0]/q mem_inst/DAC_out_reg[3][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[3][1]/q mem_inst/DAC_out_reg[3][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[3][2]/q mem_inst/DAC_out_reg[3][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[3][3]/q mem_inst/DAC_out_reg[3][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[3][4]/q mem_inst/DAC_out_reg[3][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[3][5]/q mem_inst/DAC_out_reg[3][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[3][6]/q mem_inst/DAC_out_reg[3][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[3][7]/q mem_inst/DAC_out_reg[3][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[4][0]/q mem_inst/DAC_out_reg[4][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[4][1]/q mem_inst/DAC_out_reg[4][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[4][2]/q mem_inst/DAC_out_reg[4][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[4][3]/q mem_inst/DAC_out_reg[4][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[4][4]/q mem_inst/DAC_out_reg[4][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[4][5]/q mem_inst/DAC_out_reg[4][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[4][6]/q mem_inst/DAC_out_reg[4][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[4][7]/q mem_inst/DAC_out_reg[4][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[5][0]/q mem_inst/DAC_out_reg[5][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[5][1]/q mem_inst/DAC_out_reg[5][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[5][2]/q mem_inst/DAC_out_reg[5][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[5][3]/q mem_inst/DAC_out_reg[5][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[5][4]/q mem_inst/DAC_out_reg[5][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[5][5]/q mem_inst/DAC_out_reg[5][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[5][6]/q mem_inst/DAC_out_reg[5][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[5][7]/q mem_inst/DAC_out_reg[5][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[6][0]/q mem_inst/DAC_out_reg[6][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[6][1]/q mem_inst/DAC_out_reg[6][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[6][2]/q mem_inst/DAC_out_reg[6][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[6][3]/q mem_inst/DAC_out_reg[6][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[6][4]/q mem_inst/DAC_out_reg[6][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[6][5]/q mem_inst/DAC_out_reg[6][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[6][6]/q mem_inst/DAC_out_reg[6][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[6][7]/q mem_inst/DAC_out_reg[6][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[7][0]/q mem_inst/DAC_out_reg[7][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[7][1]/q mem_inst/DAC_out_reg[7][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[7][2]/q mem_inst/DAC_out_reg[7][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[7][3]/q mem_inst/DAC_out_reg[7][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[7][4]/q mem_inst/DAC_out_reg[7][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[7][5]/q mem_inst/DAC_out_reg[7][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[7][6]/q mem_inst/DAC_out_reg[7][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[7][7]/q mem_inst/DAC_out_reg[7][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[8][0]/q mem_inst/DAC_out_reg[8][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[8][1]/q mem_inst/DAC_out_reg[8][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[8][2]/q mem_inst/DAC_out_reg[8][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[8][3]/q mem_inst/DAC_out_reg[8][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[8][4]/q mem_inst/DAC_out_reg[8][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[8][5]/q mem_inst/DAC_out_reg[8][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[8][6]/q mem_inst/DAC_out_reg[8][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[8][7]/q mem_inst/DAC_out_reg[8][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[9][0]/q mem_inst/DAC_out_reg[9][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[9][1]/q mem_inst/DAC_out_reg[9][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[9][2]/q mem_inst/DAC_out_reg[9][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[9][3]/q mem_inst/DAC_out_reg[9][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[9][4]/q mem_inst/DAC_out_reg[9][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[9][5]/q mem_inst/DAC_out_reg[9][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[9][6]/q mem_inst/DAC_out_reg[9][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[9][7]/q mem_inst/DAC_out_reg[9][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[10][0]/q mem_inst/DAC_out_reg[10][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[10][1]/q mem_inst/DAC_out_reg[10][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[10][2]/q mem_inst/DAC_out_reg[10][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[10][3]/q mem_inst/DAC_out_reg[10][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[10][4]/q mem_inst/DAC_out_reg[10][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[10][5]/q mem_inst/DAC_out_reg[10][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[10][6]/q mem_inst/DAC_out_reg[10][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[10][7]/q mem_inst/DAC_out_reg[10][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[11][0]/q mem_inst/DAC_out_reg[11][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[11][1]/q mem_inst/DAC_out_reg[11][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[11][2]/q mem_inst/DAC_out_reg[11][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[11][3]/q mem_inst/DAC_out_reg[11][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[11][4]/q mem_inst/DAC_out_reg[11][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[11][5]/q mem_inst/DAC_out_reg[11][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[11][6]/q mem_inst/DAC_out_reg[11][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[11][7]/q mem_inst/DAC_out_reg[11][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[12][0]/q mem_inst/DAC_out_reg[12][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[12][1]/q mem_inst/DAC_out_reg[12][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[12][2]/q mem_inst/DAC_out_reg[12][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[12][3]/q mem_inst/DAC_out_reg[12][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[12][4]/q mem_inst/DAC_out_reg[12][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[12][5]/q mem_inst/DAC_out_reg[12][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[12][6]/q mem_inst/DAC_out_reg[12][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[12][7]/q mem_inst/DAC_out_reg[12][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[13][0]/q mem_inst/DAC_out_reg[13][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[13][1]/q mem_inst/DAC_out_reg[13][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[13][2]/q mem_inst/DAC_out_reg[13][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[13][3]/q mem_inst/DAC_out_reg[13][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[13][4]/q mem_inst/DAC_out_reg[13][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[13][5]/q mem_inst/DAC_out_reg[13][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[13][6]/q mem_inst/DAC_out_reg[13][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[13][7]/q mem_inst/DAC_out_reg[13][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[14][0]/q mem_inst/DAC_out_reg[14][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[14][1]/q mem_inst/DAC_out_reg[14][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[14][2]/q mem_inst/DAC_out_reg[14][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[14][3]/q mem_inst/DAC_out_reg[14][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[14][4]/q mem_inst/DAC_out_reg[14][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[14][5]/q mem_inst/DAC_out_reg[14][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[14][6]/q mem_inst/DAC_out_reg[14][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[14][7]/q mem_inst/DAC_out_reg[14][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[15][0]/q mem_inst/DAC_out_reg[15][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[15][1]/q mem_inst/DAC_out_reg[15][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[15][2]/q mem_inst/DAC_out_reg[15][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[15][3]/q mem_inst/DAC_out_reg[15][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[15][4]/q mem_inst/DAC_out_reg[15][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[15][5]/q mem_inst/DAC_out_reg[15][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[15][6]/q mem_inst/DAC_out_reg[15][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[15][7]/q mem_inst/DAC_out_reg[15][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[16][0]/q mem_inst/DAC_out_reg[16][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[16][1]/q mem_inst/DAC_out_reg[16][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[16][2]/q mem_inst/DAC_out_reg[16][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[16][3]/q mem_inst/DAC_out_reg[16][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[16][4]/q mem_inst/DAC_out_reg[16][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[16][5]/q mem_inst/DAC_out_reg[16][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[16][6]/q mem_inst/DAC_out_reg[16][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[16][7]/q mem_inst/DAC_out_reg[16][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[17][0]/q mem_inst/DAC_out_reg[17][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[17][1]/q mem_inst/DAC_out_reg[17][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[17][2]/q mem_inst/DAC_out_reg[17][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[17][3]/q mem_inst/DAC_out_reg[17][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[17][4]/q mem_inst/DAC_out_reg[17][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[17][5]/q mem_inst/DAC_out_reg[17][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[17][6]/q mem_inst/DAC_out_reg[17][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[17][7]/q mem_inst/DAC_out_reg[17][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[18][0]/q mem_inst/DAC_out_reg[18][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[18][1]/q mem_inst/DAC_out_reg[18][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[18][2]/q mem_inst/DAC_out_reg[18][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[18][3]/q mem_inst/DAC_out_reg[18][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[18][4]/q mem_inst/DAC_out_reg[18][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[18][5]/q mem_inst/DAC_out_reg[18][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[18][6]/q mem_inst/DAC_out_reg[18][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[18][7]/q mem_inst/DAC_out_reg[18][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[19][0]/q mem_inst/DAC_out_reg[19][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[19][1]/q mem_inst/DAC_out_reg[19][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[19][2]/q mem_inst/DAC_out_reg[19][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[19][3]/q mem_inst/DAC_out_reg[19][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[19][4]/q mem_inst/DAC_out_reg[19][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[19][5]/q mem_inst/DAC_out_reg[19][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[19][6]/q mem_inst/DAC_out_reg[19][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[19][7]/q mem_inst/DAC_out_reg[19][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[20][0]/q mem_inst/DAC_out_reg[20][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[20][1]/q mem_inst/DAC_out_reg[20][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[20][2]/q mem_inst/DAC_out_reg[20][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[20][3]/q mem_inst/DAC_out_reg[20][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[20][4]/q mem_inst/DAC_out_reg[20][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[20][5]/q mem_inst/DAC_out_reg[20][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[20][6]/q mem_inst/DAC_out_reg[20][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[20][7]/q mem_inst/DAC_out_reg[20][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[21][0]/q mem_inst/DAC_out_reg[21][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[21][1]/q mem_inst/DAC_out_reg[21][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[21][2]/q mem_inst/DAC_out_reg[21][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[21][3]/q mem_inst/DAC_out_reg[21][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[21][4]/q mem_inst/DAC_out_reg[21][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[21][5]/q mem_inst/DAC_out_reg[21][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[21][6]/q mem_inst/DAC_out_reg[21][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[21][7]/q mem_inst/DAC_out_reg[21][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[22][0]/q mem_inst/DAC_out_reg[22][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[22][1]/q mem_inst/DAC_out_reg[22][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[22][2]/q mem_inst/DAC_out_reg[22][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[22][3]/q mem_inst/DAC_out_reg[22][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[22][4]/q mem_inst/DAC_out_reg[22][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[22][5]/q mem_inst/DAC_out_reg[22][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[22][6]/q mem_inst/DAC_out_reg[22][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[22][7]/q mem_inst/DAC_out_reg[22][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[23][0]/q mem_inst/DAC_out_reg[23][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[23][1]/q mem_inst/DAC_out_reg[23][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[23][2]/q mem_inst/DAC_out_reg[23][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[23][3]/q mem_inst/DAC_out_reg[23][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[23][4]/q mem_inst/DAC_out_reg[23][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[23][5]/q mem_inst/DAC_out_reg[23][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[23][6]/q mem_inst/DAC_out_reg[23][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[23][7]/q mem_inst/DAC_out_reg[23][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[24][0]/q mem_inst/DAC_out_reg[24][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[24][1]/q mem_inst/DAC_out_reg[24][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[24][2]/q mem_inst/DAC_out_reg[24][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[24][3]/q mem_inst/DAC_out_reg[24][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[24][4]/q mem_inst/DAC_out_reg[24][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[24][5]/q mem_inst/DAC_out_reg[24][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[24][6]/q mem_inst/DAC_out_reg[24][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[24][7]/q mem_inst/DAC_out_reg[24][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[25][0]/q mem_inst/DAC_out_reg[25][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[25][1]/q mem_inst/DAC_out_reg[25][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[25][2]/q mem_inst/DAC_out_reg[25][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[25][3]/q mem_inst/DAC_out_reg[25][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[25][4]/q mem_inst/DAC_out_reg[25][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[25][5]/q mem_inst/DAC_out_reg[25][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[25][6]/q mem_inst/DAC_out_reg[25][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[25][7]/q mem_inst/DAC_out_reg[25][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[26][0]/q mem_inst/DAC_out_reg[26][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[26][1]/q mem_inst/DAC_out_reg[26][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[26][2]/q mem_inst/DAC_out_reg[26][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[26][3]/q mem_inst/DAC_out_reg[26][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[26][4]/q mem_inst/DAC_out_reg[26][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[26][5]/q mem_inst/DAC_out_reg[26][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[26][6]/q mem_inst/DAC_out_reg[26][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[26][7]/q mem_inst/DAC_out_reg[26][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[27][0]/q mem_inst/DAC_out_reg[27][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[27][1]/q mem_inst/DAC_out_reg[27][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[27][2]/q mem_inst/DAC_out_reg[27][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[27][3]/q mem_inst/DAC_out_reg[27][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[27][4]/q mem_inst/DAC_out_reg[27][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[27][5]/q mem_inst/DAC_out_reg[27][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[27][6]/q mem_inst/DAC_out_reg[27][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[27][7]/q mem_inst/DAC_out_reg[27][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[28][0]/q mem_inst/DAC_out_reg[28][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[28][1]/q mem_inst/DAC_out_reg[28][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[28][2]/q mem_inst/DAC_out_reg[28][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[28][3]/q mem_inst/DAC_out_reg[28][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[28][4]/q mem_inst/DAC_out_reg[28][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[28][5]/q mem_inst/DAC_out_reg[28][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[28][6]/q mem_inst/DAC_out_reg[28][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[28][7]/q mem_inst/DAC_out_reg[28][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[29][0]/q mem_inst/DAC_out_reg[29][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[29][1]/q mem_inst/DAC_out_reg[29][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[29][2]/q mem_inst/DAC_out_reg[29][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[29][3]/q mem_inst/DAC_out_reg[29][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[29][4]/q mem_inst/DAC_out_reg[29][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[29][5]/q mem_inst/DAC_out_reg[29][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[29][6]/q mem_inst/DAC_out_reg[29][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[29][7]/q mem_inst/DAC_out_reg[29][7]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[30][0]/q mem_inst/DAC_out_reg[30][0]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[30][1]/q mem_inst/DAC_out_reg[30][1]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[30][2]/q mem_inst/DAC_out_reg[30][2]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[30][3]/q mem_inst/DAC_out_reg[30][3]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[30][4]/q mem_inst/DAC_out_reg[30][4]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[30][5]/q mem_inst/DAC_out_reg[30][5]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[30][6]/q mem_inst/DAC_out_reg[30][6]/Q -type DFF DFF
add mapped point mem_inst/DAC_out[30][7]/q mem_inst/DAC_out_reg[30][7]/Q -type DFF DFF
add mapped point mem_inst/Data_out[0]/q mem_inst/Data_out_reg[0]/Q -type DFF DFF
add mapped point mem_inst/Data_out[1]/q mem_inst/Data_out_reg[1]/Q -type DFF DFF
add mapped point mem_inst/Data_out[2]/q mem_inst/Data_out_reg[2]/Q -type DFF DFF
add mapped point mem_inst/Data_out[3]/q mem_inst/Data_out_reg[3]/Q -type DFF DFF
add mapped point mem_inst/Data_out[4]/q mem_inst/Data_out_reg[4]/Q -type DFF DFF
add mapped point mem_inst/Data_out[5]/q mem_inst/Data_out_reg[5]/Q -type DFF DFF
add mapped point mem_inst/Data_out[6]/q mem_inst/Data_out_reg[6]/Q -type DFF DFF
add mapped point mem_inst/Data_out[7]/q mem_inst/Data_out_reg[7]/Q -type DFF DFF
add mapped point mem_inst/Timer_EN[0]/q mem_inst/Timer_EN_reg[0]/Q -type DFF DFF
add mapped point mem_inst/Timer_EN[1]/q mem_inst/Timer_EN_reg[1]/Q -type DFF DFF
add mapped point mem_inst/Timer_EN[2]/q mem_inst/Timer_EN_reg[2]/Q -type DFF DFF
add mapped point mem_inst/Timer_FEN[0]/q mem_inst/Timer_FEN_reg[0]/Q -type DFF DFF
add mapped point mem_inst/Timer_FEN[1]/q mem_inst/Timer_FEN_reg[1]/Q -type DFF DFF
add mapped point mem_inst/Timer_FEN[2]/q mem_inst/Timer_FEN_reg[2]/Q -type DFF DFF
add mapped point mem_inst/registers_en[8]/q mem_inst/registers_en_reg[8]/Q -type DFF DFF
add mapped point mem_inst/registers_en[9]/q mem_inst/registers_en_reg[9]/Q -type DFF DFF
add mapped point mem_inst/registers_en[10]/q mem_inst/registers_en_reg[10]/Q -type DFF DFF
add mapped point mem_inst/registers_en[11]/q mem_inst/registers_en_reg[11]/Q -type DFF DFF
add mapped point mem_inst/registers_en[20]/q mem_inst/registers_en_reg[20]/Q -type DFF DFF
add mapped point mem_inst/registers_en[21]/q mem_inst/registers_en_reg[21]/Q -type DFF DFF
add mapped point mem_inst/registers_en[22]/q mem_inst/registers_en_reg[22]/Q -type DFF DFF
add mapped point mem_inst/registers_en[23]/q mem_inst/registers_en_reg[23]/Q -type DFF DFF
add mapped point mem_inst/registers_en[24]/q mem_inst/registers_en_reg[24]/Q -type DFF DFF
add mapped point mem_inst/registers_en[25]/q mem_inst/registers_en_reg[25]/Q -type DFF DFF
add mapped point mem_inst/registers_en[26]/q mem_inst/registers_en_reg[26]/Q -type DFF DFF
add mapped point mem_inst/registers_en[27]/q mem_inst/registers_en_reg[27]/Q -type DFF DFF
add mapped point mem_inst/registers_en[28]/q mem_inst/registers_en_reg[28]/Q -type DFF DFF
add mapped point mem_inst/registers_en[29]/q mem_inst/registers_en_reg[29]/Q -type DFF DFF
add mapped point mem_inst/registers_en[30]/q mem_inst/registers_en_reg[30]/Q -type DFF DFF
add mapped point mem_inst/registers_en[31]/q mem_inst/registers_en_reg[31]/Q -type DFF DFF
add mapped point mem_inst/registers_en[32]/q mem_inst/registers_en_reg[32]/Q -type DFF DFF
add mapped point mem_inst/registers_en[33]/q mem_inst/registers_en_reg[33]/Q -type DFF DFF
add mapped point mem_inst/registers[0][0]/q mem_inst/registers_reg[0][0]/Q -type DFF DFF
add mapped point mem_inst/registers[0][1]/q mem_inst/registers_reg[0][1]/Q -type DFF DFF
add mapped point mem_inst/registers[0][2]/q mem_inst/registers_reg[0][2]/Q -type DFF DFF
add mapped point mem_inst/registers[0][3]/q mem_inst/registers_reg[0][3]/Q -type DFF DFF
add mapped point mem_inst/registers[0][4]/q mem_inst/registers_reg[0][4]/Q -type DFF DFF
add mapped point mem_inst/registers[0][5]/q mem_inst/registers_reg[0][5]/Q -type DFF DFF
add mapped point mem_inst/registers[0][6]/q mem_inst/registers_reg[0][6]/Q -type DFF DFF
add mapped point mem_inst/registers[0][7]/q mem_inst/registers_reg[0][7]/Q -type DFF DFF
add mapped point mem_inst/registers[1][0]/q mem_inst/registers_reg[1][0]/Q -type DFF DFF
add mapped point mem_inst/registers[1][1]/q mem_inst/registers_reg[1][1]/Q -type DFF DFF
add mapped point mem_inst/registers[1][2]/q mem_inst/registers_reg[1][2]/Q -type DFF DFF
add mapped point mem_inst/registers[1][3]/q mem_inst/registers_reg[1][3]/Q -type DFF DFF
add mapped point mem_inst/registers[1][4]/q mem_inst/registers_reg[1][4]/Q -type DFF DFF
add mapped point mem_inst/registers[1][5]/q mem_inst/registers_reg[1][5]/Q -type DFF DFF
add mapped point mem_inst/registers[1][6]/q mem_inst/registers_reg[1][6]/Q -type DFF DFF
add mapped point mem_inst/registers[1][7]/q mem_inst/registers_reg[1][7]/Q -type DFF DFF
add mapped point mem_inst/registers[2][0]/q mem_inst/registers_reg[2][0]/Q -type DFF DFF
add mapped point mem_inst/registers[2][1]/q mem_inst/registers_reg[2][1]/Q -type DFF DFF
add mapped point mem_inst/registers[2][2]/q mem_inst/registers_reg[2][2]/Q -type DFF DFF
add mapped point mem_inst/registers[2][3]/q mem_inst/registers_reg[2][3]/Q -type DFF DFF
add mapped point mem_inst/registers[2][4]/q mem_inst/registers_reg[2][4]/Q -type DFF DFF
add mapped point mem_inst/registers[2][5]/q mem_inst/registers_reg[2][5]/Q -type DFF DFF
add mapped point mem_inst/registers[2][6]/q mem_inst/registers_reg[2][6]/Q -type DFF DFF
add mapped point mem_inst/registers[2][7]/q mem_inst/registers_reg[2][7]/Q -type DFF DFF
add mapped point mem_inst/registers[3][0]/q mem_inst/registers_reg[3][0]/Q -type DFF DFF
add mapped point mem_inst/registers[3][1]/q mem_inst/registers_reg[3][1]/Q -type DFF DFF
add mapped point mem_inst/registers[3][2]/q mem_inst/registers_reg[3][2]/Q -type DFF DFF
add mapped point mem_inst/registers[3][3]/q mem_inst/registers_reg[3][3]/Q -type DFF DFF
add mapped point mem_inst/registers[3][4]/q mem_inst/registers_reg[3][4]/Q -type DFF DFF
add mapped point mem_inst/registers[3][5]/q mem_inst/registers_reg[3][5]/Q -type DFF DFF
add mapped point mem_inst/registers[3][6]/q mem_inst/registers_reg[3][6]/Q -type DFF DFF
add mapped point mem_inst/registers[3][7]/q mem_inst/registers_reg[3][7]/Q -type DFF DFF
add mapped point mem_inst/registers[4][0]/q mem_inst/registers_reg[4][0]/Q -type DFF DFF
add mapped point mem_inst/registers[4][1]/q mem_inst/registers_reg[4][1]/Q -type DFF DFF
add mapped point mem_inst/registers[4][2]/q mem_inst/registers_reg[4][2]/Q -type DFF DFF
add mapped point mem_inst/registers[4][3]/q mem_inst/registers_reg[4][3]/Q -type DFF DFF
add mapped point mem_inst/registers[4][4]/q mem_inst/registers_reg[4][4]/Q -type DFF DFF
add mapped point mem_inst/registers[4][5]/q mem_inst/registers_reg[4][5]/Q -type DFF DFF
add mapped point mem_inst/registers[4][6]/q mem_inst/registers_reg[4][6]/Q -type DFF DFF
add mapped point mem_inst/registers[4][7]/q mem_inst/registers_reg[4][7]/Q -type DFF DFF
add mapped point mem_inst/registers[5][0]/q mem_inst/registers_reg[5][0]/Q -type DFF DFF
add mapped point mem_inst/registers[5][1]/q mem_inst/registers_reg[5][1]/Q -type DFF DFF
add mapped point mem_inst/registers[5][2]/q mem_inst/registers_reg[5][2]/Q -type DFF DFF
add mapped point mem_inst/registers[5][3]/q mem_inst/registers_reg[5][3]/Q -type DFF DFF
add mapped point mem_inst/registers[5][4]/q mem_inst/registers_reg[5][4]/Q -type DFF DFF
add mapped point mem_inst/registers[5][5]/q mem_inst/registers_reg[5][5]/Q -type DFF DFF
add mapped point mem_inst/registers[5][6]/q mem_inst/registers_reg[5][6]/Q -type DFF DFF
add mapped point mem_inst/registers[5][7]/q mem_inst/registers_reg[5][7]/Q -type DFF DFF
add mapped point mem_inst/registers[6][0]/q mem_inst/registers_reg[6][0]/Q -type DFF DFF
add mapped point mem_inst/registers[6][1]/q mem_inst/registers_reg[6][1]/Q -type DFF DFF
add mapped point mem_inst/registers[6][2]/q mem_inst/registers_reg[6][2]/Q -type DFF DFF
add mapped point mem_inst/registers[6][3]/q mem_inst/registers_reg[6][3]/Q -type DFF DFF
add mapped point mem_inst/registers[6][4]/q mem_inst/registers_reg[6][4]/Q -type DFF DFF
add mapped point mem_inst/registers[6][5]/q mem_inst/registers_reg[6][5]/Q -type DFF DFF
add mapped point mem_inst/registers[6][6]/q mem_inst/registers_reg[6][6]/Q -type DFF DFF
add mapped point mem_inst/registers[6][7]/q mem_inst/registers_reg[6][7]/Q -type DFF DFF
add mapped point mem_inst/registers[7][0]/q mem_inst/registers_reg[7][0]/Q -type DFF DFF
add mapped point mem_inst/registers[7][1]/q mem_inst/registers_reg[7][1]/Q -type DFF DFF
add mapped point mem_inst/registers[7][2]/q mem_inst/registers_reg[7][2]/Q -type DFF DFF
add mapped point mem_inst/registers[7][3]/q mem_inst/registers_reg[7][3]/Q -type DFF DFF
add mapped point mem_inst/registers[7][4]/q mem_inst/registers_reg[7][4]/Q -type DFF DFF
add mapped point mem_inst/registers[7][5]/q mem_inst/registers_reg[7][5]/Q -type DFF DFF
add mapped point mem_inst/registers[7][6]/q mem_inst/registers_reg[7][6]/Q -type DFF DFF
add mapped point mem_inst/registers[7][7]/q mem_inst/registers_reg[7][7]/Q -type DFF DFF
add mapped point mem_inst/registers[8][0]/q mem_inst/registers_reg[8][0]/Q -type DFF DFF
add mapped point mem_inst/registers[8][1]/q mem_inst/registers_reg[8][1]/Q -type DFF DFF
add mapped point mem_inst/registers[8][2]/q mem_inst/registers_reg[8][2]/Q -type DFF DFF
add mapped point mem_inst/registers[8][3]/q mem_inst/registers_reg[8][3]/Q -type DFF DFF
add mapped point mem_inst/registers[8][4]/q mem_inst/registers_reg[8][4]/Q -type DFF DFF
add mapped point mem_inst/registers[8][5]/q mem_inst/registers_reg[8][5]/Q -type DFF DFF
add mapped point mem_inst/registers[8][6]/q mem_inst/registers_reg[8][6]/Q -type DFF DFF
add mapped point mem_inst/registers[8][7]/q mem_inst/registers_reg[8][7]/Q -type DFF DFF
add mapped point mem_inst/registers[9][0]/q mem_inst/registers_reg[9][0]/Q -type DFF DFF
add mapped point mem_inst/registers[9][1]/q mem_inst/registers_reg[9][1]/Q -type DFF DFF
add mapped point mem_inst/registers[9][2]/q mem_inst/registers_reg[9][2]/Q -type DFF DFF
add mapped point mem_inst/registers[9][3]/q mem_inst/registers_reg[9][3]/Q -type DFF DFF
add mapped point mem_inst/registers[9][4]/q mem_inst/registers_reg[9][4]/Q -type DFF DFF
add mapped point mem_inst/registers[9][5]/q mem_inst/registers_reg[9][5]/Q -type DFF DFF
add mapped point mem_inst/registers[9][6]/q mem_inst/registers_reg[9][6]/Q -type DFF DFF
add mapped point mem_inst/registers[9][7]/q mem_inst/registers_reg[9][7]/Q -type DFF DFF
add mapped point mem_inst/registers[10][0]/q mem_inst/registers_reg[10][0]/Q -type DFF DFF
add mapped point mem_inst/registers[10][1]/q mem_inst/registers_reg[10][1]/Q -type DFF DFF
add mapped point mem_inst/registers[10][2]/q mem_inst/registers_reg[10][2]/Q -type DFF DFF
add mapped point mem_inst/registers[10][3]/q mem_inst/registers_reg[10][3]/Q -type DFF DFF
add mapped point mem_inst/registers[10][4]/q mem_inst/registers_reg[10][4]/Q -type DFF DFF
add mapped point mem_inst/registers[10][5]/q mem_inst/registers_reg[10][5]/Q -type DFF DFF
add mapped point mem_inst/registers[10][6]/q mem_inst/registers_reg[10][6]/Q -type DFF DFF
add mapped point mem_inst/registers[10][7]/q mem_inst/registers_reg[10][7]/Q -type DFF DFF
add mapped point mem_inst/registers[11][0]/q mem_inst/registers_reg[11][0]/Q -type DFF DFF
add mapped point mem_inst/registers[11][1]/q mem_inst/registers_reg[11][1]/Q -type DFF DFF
add mapped point mem_inst/registers[11][2]/q mem_inst/registers_reg[11][2]/Q -type DFF DFF
add mapped point mem_inst/registers[11][3]/q mem_inst/registers_reg[11][3]/Q -type DFF DFF
add mapped point mem_inst/registers[11][4]/q mem_inst/registers_reg[11][4]/Q -type DFF DFF
add mapped point mem_inst/registers[11][5]/q mem_inst/registers_reg[11][5]/Q -type DFF DFF
add mapped point mem_inst/registers[11][6]/q mem_inst/registers_reg[11][6]/Q -type DFF DFF
add mapped point mem_inst/registers[11][7]/q mem_inst/registers_reg[11][7]/Q -type DFF DFF
add mapped point mem_inst/registers[12][0]/q mem_inst/registers_reg[12][0]/Q -type DFF DFF
add mapped point mem_inst/registers[12][1]/q mem_inst/registers_reg[12][1]/Q -type DFF DFF
add mapped point mem_inst/registers[12][2]/q mem_inst/registers_reg[12][2]/Q -type DFF DFF
add mapped point mem_inst/registers[12][3]/q mem_inst/registers_reg[12][3]/Q -type DFF DFF
add mapped point mem_inst/registers[12][4]/q mem_inst/registers_reg[12][4]/Q -type DFF DFF
add mapped point mem_inst/registers[12][5]/q mem_inst/registers_reg[12][5]/Q -type DFF DFF
add mapped point mem_inst/registers[12][6]/q mem_inst/registers_reg[12][6]/Q -type DFF DFF
add mapped point mem_inst/registers[12][7]/q mem_inst/registers_reg[12][7]/Q -type DFF DFF
add mapped point mem_inst/registers[13][0]/q mem_inst/registers_reg[13][0]/Q -type DFF DFF
add mapped point mem_inst/registers[13][1]/q mem_inst/registers_reg[13][1]/Q -type DFF DFF
add mapped point mem_inst/registers[13][2]/q mem_inst/registers_reg[13][2]/Q -type DFF DFF
add mapped point mem_inst/registers[13][3]/q mem_inst/registers_reg[13][3]/Q -type DFF DFF
add mapped point mem_inst/registers[13][4]/q mem_inst/registers_reg[13][4]/Q -type DFF DFF
add mapped point mem_inst/registers[13][5]/q mem_inst/registers_reg[13][5]/Q -type DFF DFF
add mapped point mem_inst/registers[13][6]/q mem_inst/registers_reg[13][6]/Q -type DFF DFF
add mapped point mem_inst/registers[13][7]/q mem_inst/registers_reg[13][7]/Q -type DFF DFF
add mapped point mem_inst/registers[14][0]/q mem_inst/registers_reg[14][0]/Q -type DFF DFF
add mapped point mem_inst/registers[14][1]/q mem_inst/registers_reg[14][1]/Q -type DFF DFF
add mapped point mem_inst/registers[14][2]/q mem_inst/registers_reg[14][2]/Q -type DFF DFF
add mapped point mem_inst/registers[14][3]/q mem_inst/registers_reg[14][3]/Q -type DFF DFF
add mapped point mem_inst/registers[14][4]/q mem_inst/registers_reg[14][4]/Q -type DFF DFF
add mapped point mem_inst/registers[14][5]/q mem_inst/registers_reg[14][5]/Q -type DFF DFF
add mapped point mem_inst/registers[14][6]/q mem_inst/registers_reg[14][6]/Q -type DFF DFF
add mapped point mem_inst/registers[14][7]/q mem_inst/registers_reg[14][7]/Q -type DFF DFF
add mapped point mem_inst/registers[15][0]/q mem_inst/registers_reg[15][0]/Q -type DFF DFF
add mapped point mem_inst/registers[15][1]/q mem_inst/registers_reg[15][1]/Q -type DFF DFF
add mapped point mem_inst/registers[15][2]/q mem_inst/registers_reg[15][2]/Q -type DFF DFF
add mapped point mem_inst/registers[15][3]/q mem_inst/registers_reg[15][3]/Q -type DFF DFF
add mapped point mem_inst/registers[15][4]/q mem_inst/registers_reg[15][4]/Q -type DFF DFF
add mapped point mem_inst/registers[15][5]/q mem_inst/registers_reg[15][5]/Q -type DFF DFF
add mapped point mem_inst/registers[15][6]/q mem_inst/registers_reg[15][6]/Q -type DFF DFF
add mapped point mem_inst/registers[15][7]/q mem_inst/registers_reg[15][7]/Q -type DFF DFF
add mapped point mem_inst/registers[16][0]/q mem_inst/registers_reg[16][0]/Q -type DFF DFF
add mapped point mem_inst/registers[16][1]/q mem_inst/registers_reg[16][1]/Q -type DFF DFF
add mapped point mem_inst/registers[16][2]/q mem_inst/registers_reg[16][2]/Q -type DFF DFF
add mapped point mem_inst/registers[16][3]/q mem_inst/registers_reg[16][3]/Q -type DFF DFF
add mapped point mem_inst/registers[16][4]/q mem_inst/registers_reg[16][4]/Q -type DFF DFF
add mapped point mem_inst/registers[16][5]/q mem_inst/registers_reg[16][5]/Q -type DFF DFF
add mapped point mem_inst/registers[16][6]/q mem_inst/registers_reg[16][6]/Q -type DFF DFF
add mapped point mem_inst/registers[16][7]/q mem_inst/registers_reg[16][7]/Q -type DFF DFF
add mapped point mem_inst/registers[17][0]/q mem_inst/registers_reg[17][0]/Q -type DFF DFF
add mapped point mem_inst/registers[17][1]/q mem_inst/registers_reg[17][1]/Q -type DFF DFF
add mapped point mem_inst/registers[17][2]/q mem_inst/registers_reg[17][2]/Q -type DFF DFF
add mapped point mem_inst/registers[17][3]/q mem_inst/registers_reg[17][3]/Q -type DFF DFF
add mapped point mem_inst/registers[17][4]/q mem_inst/registers_reg[17][4]/Q -type DFF DFF
add mapped point mem_inst/registers[17][5]/q mem_inst/registers_reg[17][5]/Q -type DFF DFF
add mapped point mem_inst/registers[17][6]/q mem_inst/registers_reg[17][6]/Q -type DFF DFF
add mapped point mem_inst/registers[17][7]/q mem_inst/registers_reg[17][7]/Q -type DFF DFF
add mapped point mem_inst/registers[18][0]/q mem_inst/registers_reg[18][0]/Q -type DFF DFF
add mapped point mem_inst/registers[18][1]/q mem_inst/registers_reg[18][1]/Q -type DFF DFF
add mapped point mem_inst/registers[18][2]/q mem_inst/registers_reg[18][2]/Q -type DFF DFF
add mapped point mem_inst/registers[18][3]/q mem_inst/registers_reg[18][3]/Q -type DFF DFF
add mapped point mem_inst/registers[18][4]/q mem_inst/registers_reg[18][4]/Q -type DFF DFF
add mapped point mem_inst/registers[18][5]/q mem_inst/registers_reg[18][5]/Q -type DFF DFF
add mapped point mem_inst/registers[18][6]/q mem_inst/registers_reg[18][6]/Q -type DFF DFF
add mapped point mem_inst/registers[18][7]/q mem_inst/registers_reg[18][7]/Q -type DFF DFF
add mapped point mem_inst/registers[19][0]/q mem_inst/registers_reg[19][0]/Q -type DFF DFF
add mapped point mem_inst/registers[19][1]/q mem_inst/registers_reg[19][1]/Q -type DFF DFF
add mapped point mem_inst/registers[19][2]/q mem_inst/registers_reg[19][2]/Q -type DFF DFF
add mapped point mem_inst/registers[19][3]/q mem_inst/registers_reg[19][3]/Q -type DFF DFF
add mapped point mem_inst/registers[19][4]/q mem_inst/registers_reg[19][4]/Q -type DFF DFF
add mapped point mem_inst/registers[19][5]/q mem_inst/registers_reg[19][5]/Q -type DFF DFF
add mapped point mem_inst/registers[19][6]/q mem_inst/registers_reg[19][6]/Q -type DFF DFF
add mapped point mem_inst/registers[19][7]/q mem_inst/registers_reg[19][7]/Q -type DFF DFF
add mapped point mem_inst/registers[20][0]/q mem_inst/registers_reg[20][0]/Q -type DFF DFF
add mapped point mem_inst/registers[20][1]/q mem_inst/registers_reg[20][1]/Q -type DFF DFF
add mapped point mem_inst/registers[20][2]/q mem_inst/registers_reg[20][2]/Q -type DFF DFF
add mapped point mem_inst/registers[20][3]/q mem_inst/registers_reg[20][3]/Q -type DFF DFF
add mapped point mem_inst/registers[20][4]/q mem_inst/registers_reg[20][4]/Q -type DFF DFF
add mapped point mem_inst/registers[20][5]/q mem_inst/registers_reg[20][5]/Q -type DFF DFF
add mapped point mem_inst/registers[20][6]/q mem_inst/registers_reg[20][6]/Q -type DFF DFF
add mapped point mem_inst/registers[20][7]/q mem_inst/registers_reg[20][7]/Q -type DFF DFF
add mapped point mem_inst/registers[21][0]/q mem_inst/registers_reg[21][0]/Q -type DFF DFF
add mapped point mem_inst/registers[21][1]/q mem_inst/registers_reg[21][1]/Q -type DFF DFF
add mapped point mem_inst/registers[21][2]/q mem_inst/registers_reg[21][2]/Q -type DFF DFF
add mapped point mem_inst/registers[21][3]/q mem_inst/registers_reg[21][3]/Q -type DFF DFF
add mapped point mem_inst/registers[21][4]/q mem_inst/registers_reg[21][4]/Q -type DFF DFF
add mapped point mem_inst/registers[21][5]/q mem_inst/registers_reg[21][5]/Q -type DFF DFF
add mapped point mem_inst/registers[21][6]/q mem_inst/registers_reg[21][6]/Q -type DFF DFF
add mapped point mem_inst/registers[21][7]/q mem_inst/registers_reg[21][7]/Q -type DFF DFF
add mapped point mem_inst/registers[22][0]/q mem_inst/registers_reg[22][0]/Q -type DFF DFF
add mapped point mem_inst/registers[22][1]/q mem_inst/registers_reg[22][1]/Q -type DFF DFF
add mapped point mem_inst/registers[22][2]/q mem_inst/registers_reg[22][2]/Q -type DFF DFF
add mapped point mem_inst/registers[22][3]/q mem_inst/registers_reg[22][3]/Q -type DFF DFF
add mapped point mem_inst/registers[22][4]/q mem_inst/registers_reg[22][4]/Q -type DFF DFF
add mapped point mem_inst/registers[22][5]/q mem_inst/registers_reg[22][5]/Q -type DFF DFF
add mapped point mem_inst/registers[22][6]/q mem_inst/registers_reg[22][6]/Q -type DFF DFF
add mapped point mem_inst/registers[22][7]/q mem_inst/registers_reg[22][7]/Q -type DFF DFF
add mapped point mem_inst/registers[23][0]/q mem_inst/registers_reg[23][0]/Q -type DFF DFF
add mapped point mem_inst/registers[23][1]/q mem_inst/registers_reg[23][1]/Q -type DFF DFF
add mapped point mem_inst/registers[23][2]/q mem_inst/registers_reg[23][2]/Q -type DFF DFF
add mapped point mem_inst/registers[23][3]/q mem_inst/registers_reg[23][3]/Q -type DFF DFF
add mapped point mem_inst/registers[23][4]/q mem_inst/registers_reg[23][4]/Q -type DFF DFF
add mapped point mem_inst/registers[23][5]/q mem_inst/registers_reg[23][5]/Q -type DFF DFF
add mapped point mem_inst/registers[23][6]/q mem_inst/registers_reg[23][6]/Q -type DFF DFF
add mapped point mem_inst/registers[23][7]/q mem_inst/registers_reg[23][7]/Q -type DFF DFF
add mapped point mem_inst/registers[24][0]/q mem_inst/registers_reg[24][0]/Q -type DFF DFF
add mapped point mem_inst/registers[24][1]/q mem_inst/registers_reg[24][1]/Q -type DFF DFF
add mapped point mem_inst/registers[24][2]/q mem_inst/registers_reg[24][2]/Q -type DFF DFF
add mapped point mem_inst/registers[24][3]/q mem_inst/registers_reg[24][3]/Q -type DFF DFF
add mapped point mem_inst/registers[24][4]/q mem_inst/registers_reg[24][4]/Q -type DFF DFF
add mapped point mem_inst/registers[24][5]/q mem_inst/registers_reg[24][5]/Q -type DFF DFF
add mapped point mem_inst/registers[24][6]/q mem_inst/registers_reg[24][6]/Q -type DFF DFF
add mapped point mem_inst/registers[24][7]/q mem_inst/registers_reg[24][7]/Q -type DFF DFF
add mapped point mem_inst/registers[25][0]/q mem_inst/registers_reg[25][0]/Q -type DFF DFF
add mapped point mem_inst/registers[25][1]/q mem_inst/registers_reg[25][1]/Q -type DFF DFF
add mapped point mem_inst/registers[25][2]/q mem_inst/registers_reg[25][2]/Q -type DFF DFF
add mapped point mem_inst/registers[25][3]/q mem_inst/registers_reg[25][3]/Q -type DFF DFF
add mapped point mem_inst/registers[25][4]/q mem_inst/registers_reg[25][4]/Q -type DFF DFF
add mapped point mem_inst/registers[25][5]/q mem_inst/registers_reg[25][5]/Q -type DFF DFF
add mapped point mem_inst/registers[25][6]/q mem_inst/registers_reg[25][6]/Q -type DFF DFF
add mapped point mem_inst/registers[25][7]/q mem_inst/registers_reg[25][7]/Q -type DFF DFF
add mapped point mem_inst/registers[26][0]/q mem_inst/registers_reg[26][0]/Q -type DFF DFF
add mapped point mem_inst/registers[26][1]/q mem_inst/registers_reg[26][1]/Q -type DFF DFF
add mapped point mem_inst/registers[26][2]/q mem_inst/registers_reg[26][2]/Q -type DFF DFF
add mapped point mem_inst/registers[26][3]/q mem_inst/registers_reg[26][3]/Q -type DFF DFF
add mapped point mem_inst/registers[26][4]/q mem_inst/registers_reg[26][4]/Q -type DFF DFF
add mapped point mem_inst/registers[26][5]/q mem_inst/registers_reg[26][5]/Q -type DFF DFF
add mapped point mem_inst/registers[26][6]/q mem_inst/registers_reg[26][6]/Q -type DFF DFF
add mapped point mem_inst/registers[26][7]/q mem_inst/registers_reg[26][7]/Q -type DFF DFF
add mapped point mem_inst/registers[27][0]/q mem_inst/registers_reg[27][0]/Q -type DFF DFF
add mapped point mem_inst/registers[27][1]/q mem_inst/registers_reg[27][1]/Q -type DFF DFF
add mapped point mem_inst/registers[27][2]/q mem_inst/registers_reg[27][2]/Q -type DFF DFF
add mapped point mem_inst/registers[27][3]/q mem_inst/registers_reg[27][3]/Q -type DFF DFF
add mapped point mem_inst/registers[27][4]/q mem_inst/registers_reg[27][4]/Q -type DFF DFF
add mapped point mem_inst/registers[27][5]/q mem_inst/registers_reg[27][5]/Q -type DFF DFF
add mapped point mem_inst/registers[27][6]/q mem_inst/registers_reg[27][6]/Q -type DFF DFF
add mapped point mem_inst/registers[27][7]/q mem_inst/registers_reg[27][7]/Q -type DFF DFF
add mapped point mem_inst/registers[28][0]/q mem_inst/registers_reg[28][0]/Q -type DFF DFF
add mapped point mem_inst/registers[28][1]/q mem_inst/registers_reg[28][1]/Q -type DFF DFF
add mapped point mem_inst/registers[28][2]/q mem_inst/registers_reg[28][2]/Q -type DFF DFF
add mapped point mem_inst/registers[28][3]/q mem_inst/registers_reg[28][3]/Q -type DFF DFF
add mapped point mem_inst/registers[28][4]/q mem_inst/registers_reg[28][4]/Q -type DFF DFF
add mapped point mem_inst/registers[28][5]/q mem_inst/registers_reg[28][5]/Q -type DFF DFF
add mapped point mem_inst/registers[28][6]/q mem_inst/registers_reg[28][6]/Q -type DFF DFF
add mapped point mem_inst/registers[28][7]/q mem_inst/registers_reg[28][7]/Q -type DFF DFF
add mapped point mem_inst/registers[29][0]/q mem_inst/registers_reg[29][0]/Q -type DFF DFF
add mapped point mem_inst/registers[29][1]/q mem_inst/registers_reg[29][1]/Q -type DFF DFF
add mapped point mem_inst/registers[29][2]/q mem_inst/registers_reg[29][2]/Q -type DFF DFF
add mapped point mem_inst/registers[29][3]/q mem_inst/registers_reg[29][3]/Q -type DFF DFF
add mapped point mem_inst/registers[29][4]/q mem_inst/registers_reg[29][4]/Q -type DFF DFF
add mapped point mem_inst/registers[29][5]/q mem_inst/registers_reg[29][5]/Q -type DFF DFF
add mapped point mem_inst/registers[29][6]/q mem_inst/registers_reg[29][6]/Q -type DFF DFF
add mapped point mem_inst/registers[29][7]/q mem_inst/registers_reg[29][7]/Q -type DFF DFF
add mapped point mem_inst/registers[30][0]/q mem_inst/registers_reg[30][0]/Q -type DFF DFF
add mapped point mem_inst/registers[30][1]/q mem_inst/registers_reg[30][1]/Q -type DFF DFF
add mapped point mem_inst/registers[30][2]/q mem_inst/registers_reg[30][2]/Q -type DFF DFF
add mapped point mem_inst/registers[30][3]/q mem_inst/registers_reg[30][3]/Q -type DFF DFF
add mapped point mem_inst/registers[30][4]/q mem_inst/registers_reg[30][4]/Q -type DFF DFF
add mapped point mem_inst/registers[30][5]/q mem_inst/registers_reg[30][5]/Q -type DFF DFF
add mapped point mem_inst/registers[30][6]/q mem_inst/registers_reg[30][6]/Q -type DFF DFF
add mapped point mem_inst/registers[30][7]/q mem_inst/registers_reg[30][7]/Q -type DFF DFF
add mapped point mem_inst/registers[31][0]/q mem_inst/registers_reg[31][0]/Q -type DFF DFF
add mapped point mem_inst/registers[31][1]/q mem_inst/registers_reg[31][1]/Q -type DFF DFF
add mapped point mem_inst/registers[31][2]/q mem_inst/registers_reg[31][2]/Q -type DFF DFF
add mapped point mem_inst/registers[31][3]/q mem_inst/registers_reg[31][3]/Q -type DFF DFF
add mapped point mem_inst/registers[31][4]/q mem_inst/registers_reg[31][4]/Q -type DFF DFF
add mapped point mem_inst/registers[31][5]/q mem_inst/registers_reg[31][5]/Q -type DFF DFF
add mapped point mem_inst/registers[31][6]/q mem_inst/registers_reg[31][6]/Q -type DFF DFF
add mapped point mem_inst/registers[31][7]/q mem_inst/registers_reg[31][7]/Q -type DFF DFF
add mapped point mem_inst/registers[32][0]/q mem_inst/registers_reg[32][0]/Q -type DFF DFF
add mapped point mem_inst/registers[32][1]/q mem_inst/registers_reg[32][1]/Q -type DFF DFF
add mapped point mem_inst/registers[32][2]/q mem_inst/registers_reg[32][2]/Q -type DFF DFF
add mapped point mem_inst/registers[32][3]/q mem_inst/registers_reg[32][3]/Q -type DFF DFF
add mapped point mem_inst/registers[32][4]/q mem_inst/registers_reg[32][4]/Q -type DFF DFF
add mapped point mem_inst/registers[32][5]/q mem_inst/registers_reg[32][5]/Q -type DFF DFF
add mapped point mem_inst/registers[32][6]/q mem_inst/registers_reg[32][6]/Q -type DFF DFF
add mapped point mem_inst/registers[32][7]/q mem_inst/registers_reg[32][7]/Q -type DFF DFF
add mapped point mem_inst/registers[33][0]/q mem_inst/registers_reg[33][0]/Q -type DFF DFF
add mapped point mem_inst/registers[33][1]/q mem_inst/registers_reg[33][1]/Q -type DFF DFF
add mapped point mem_inst/registers[33][2]/q mem_inst/registers_reg[33][2]/Q -type DFF DFF
add mapped point mem_inst/registers[33][3]/q mem_inst/registers_reg[33][3]/Q -type DFF DFF
add mapped point mem_inst/registers[33][4]/q mem_inst/registers_reg[33][4]/Q -type DFF DFF
add mapped point mem_inst/registers[33][5]/q mem_inst/registers_reg[33][5]/Q -type DFF DFF
add mapped point mem_inst/registers[33][6]/q mem_inst/registers_reg[33][6]/Q -type DFF DFF
add mapped point mem_inst/registers[33][7]/q mem_inst/registers_reg[33][7]/Q -type DFF DFF
add mapped point mem_inst/registers[34][0]/q mem_inst/registers_reg[34][0]/Q -type DFF DFF
add mapped point mem_inst/registers[34][1]/q mem_inst/registers_reg[34][1]/Q -type DFF DFF
add mapped point mem_inst/registers[34][2]/q mem_inst/registers_reg[34][2]/Q -type DFF DFF
add mapped point mem_inst/registers[34][3]/q mem_inst/registers_reg[34][3]/Q -type DFF DFF
add mapped point mem_inst/registers[34][4]/q mem_inst/registers_reg[34][4]/Q -type DFF DFF
add mapped point mem_inst/registers[34][5]/q mem_inst/registers_reg[34][5]/Q -type DFF DFF
add mapped point mem_inst/registers[34][6]/q mem_inst/registers_reg[34][6]/Q -type DFF DFF
add mapped point mem_inst/registers[34][7]/q mem_inst/registers_reg[34][7]/Q -type DFF DFF
add mapped point mem_inst/registers[35][0]/q mem_inst/registers_reg[35][0]/Q -type DFF DFF
add mapped point mem_inst/registers[35][1]/q mem_inst/registers_reg[35][1]/Q -type DFF DFF
add mapped point mem_inst/registers[35][2]/q mem_inst/registers_reg[35][2]/Q -type DFF DFF
add mapped point mem_inst/registers[35][3]/q mem_inst/registers_reg[35][3]/Q -type DFF DFF
add mapped point mem_inst/registers[35][4]/q mem_inst/registers_reg[35][4]/Q -type DFF DFF
add mapped point mem_inst/registers[35][5]/q mem_inst/registers_reg[35][5]/Q -type DFF DFF
add mapped point mem_inst/registers[35][6]/q mem_inst/registers_reg[35][6]/Q -type DFF DFF
add mapped point mem_inst/registers[35][7]/q mem_inst/registers_reg[35][7]/Q -type DFF DFF
add mapped point mem_inst/registers[36][0]/q mem_inst/registers_reg[36][0]/Q -type DFF DFF
add mapped point mem_inst/registers[36][1]/q mem_inst/registers_reg[36][1]/Q -type DFF DFF
add mapped point mem_inst/registers[36][2]/q mem_inst/registers_reg[36][2]/Q -type DFF DFF
add mapped point mem_inst/registers[36][3]/q mem_inst/registers_reg[36][3]/Q -type DFF DFF
add mapped point mem_inst/registers[36][4]/q mem_inst/registers_reg[36][4]/Q -type DFF DFF
add mapped point mem_inst/registers[36][5]/q mem_inst/registers_reg[36][5]/Q -type DFF DFF
add mapped point mem_inst/registers[36][6]/q mem_inst/registers_reg[36][6]/Q -type DFF DFF
add mapped point mem_inst/registers[36][7]/q mem_inst/registers_reg[36][7]/Q -type DFF DFF
add mapped point mem_inst/rw_en/q mem_inst/rw_en_reg/Q -type DFF DFF
add mapped point mem_inst/registers_en[0]/q mem_inst/registers_en_reg[0]/Q -type DFF DFF
add mapped point mem_inst/registers_en[1]/q mem_inst/registers_en_reg[1]/Q -type DFF DFF
add mapped point mem_inst/registers_en[2]/q mem_inst/registers_en_reg[2]/Q -type DFF DFF
add mapped point mem_inst/registers_en[3]/q mem_inst/registers_en_reg[3]/Q -type DFF DFF
add mapped point mem_inst/registers_en[4]/q mem_inst/registers_en_reg[4]/Q -type DFF DFF
add mapped point mem_inst/registers_en[5]/q mem_inst/registers_en_reg[5]/Q -type DFF DFF
add mapped point mem_inst/registers_en[6]/q mem_inst/registers_en_reg[6]/Q -type DFF DFF
add mapped point mem_inst/registers_en[7]/q mem_inst/registers_en_reg[7]/Q -type DFF DFF
add mapped point mem_inst/registers_en[12]/q mem_inst/registers_en_reg[12]/Q -type DFF DFF
add mapped point mem_inst/registers_en[13]/q mem_inst/registers_en_reg[13]/Q -type DFF DFF
add mapped point mem_inst/registers_en[14]/q mem_inst/registers_en_reg[14]/Q -type DFF DFF
add mapped point mem_inst/registers_en[15]/q mem_inst/registers_en_reg[15]/Q -type DFF DFF
add mapped point mem_inst/registers_en[16]/q mem_inst/registers_en_reg[16]/Q -type DFF DFF
add mapped point mem_inst/registers_en[17]/q mem_inst/registers_en_reg[17]/Q -type DFF DFF
add mapped point mem_inst/registers_en[18]/q mem_inst/registers_en_reg[18]/Q -type DFF DFF
add mapped point mem_inst/registers_en[19]/q mem_inst/registers_en_reg[19]/Q -type DFF DFF
add mapped point mem_inst/registers_en[34]/q mem_inst/registers_en_reg[34]/Q -type DFF DFF
add mapped point mem_inst/registers_en[35]/q mem_inst/registers_en_reg[35]/Q -type DFF DFF
add mapped point mem_inst/registers_en[36]/q mem_inst/registers_en_reg[36]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
