#
# Voltus Scheduler command file generated by voltus_rail on Tue Feb 17 14:49:35 2026
#
setvar log_file ./work/voltus_extractor.log
extracted_nets vdd 
setvar output_cache_directory_name /tmp/innovus_temp_146358_cn89.it.auth.gr_paschalk_LseSCo/zx_tmp_cn89.it.auth.gr_158147
setvar library_name ./rail_final/era_work/incremental_output0/pgv/techonly.cl
setvar output_directory_name ./work
setvar output_file_name vdd
setvar max_error_messages 100
setvar max_resistor_length 800
setvar hierarchy_char /
layout_file /tmp/innovus_temp_146358_cn89.it.auth.gr_paschalk_LseSCo/eps_out_146358.def.gz  
setvar exec_token "/tmp/innovus_temp_146358_cn89.it.auth.gr_paschalk_LseSCo/eps_out_146358.def.gz"
setvar enable_signal_via_overhang false
setvar zx_multinet_extraction false
setvar extraction_mode early
setvar enable_zx_report_shorts true
extraction_type all none
extraction_type pattern vdd r_only
hierarchical_path_tracer netinst_table ./work/vdd.netinst
hierarchical_path_tracer cell_table ./work/vdd.cellinst
setvar output_wlt drawn
setvar use_hpt_leqnets_info true
label port vddvsrc1 10.5600 6.0300 METTPL
hierarchical_path_tracer pgnet_table ./work/all.pgnets
setvar output_def false
setvar cluster_via_size 25
setvar cluster_via1_maximum true
setvar def_merge_supply_shorts false
setvar promote_ports true
setvar max_cpu 1
setvar tech_file Libs/QRS_PVS/Max/qrcTechFile
setvar density_check_method database
setvar sfedb_path ./work/SFEDB 
setvar enable_binary_inst_pgdb true
setvar keep_log_file false
